runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)

- url: /static
  static_dir: static

- url: /quote/.*
  script: main.app

libraries:
- name: ssl
  version: latest
