runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /quote.*
  script: main.app

- url: /static
  static_dir: static

- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /(.*\..*)
  static_files: www/\1
  upload: www/(.*)

libraries:
- name: ssl
  version: latest
